#配置数据源druid
spring:
  datasource:
    username: xjj
    password: 18178595973lyj
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.208.59:4306/onepanda?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&allowMultiQueries=true
    initialization-mode: always

    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters,去掉后监控界面sql无法统计
    filters: stat
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
    data-password:

  #文件上传的配置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB

  #腾讯云存储桶的配置,path用于返回访问路径
  tengxun:
    secretId: AKID2vb2DJdAmzHLAnrOGyTkorhJhGEyoPnC
    secretKey: Rfe4EBtJTGsHQKisnRrDessfEZfroX1G
    onePandaBucket: one-panda-1257831346
    area: ap-shanghai
    path: https://one-panda-1257831346.cos.ap-shanghai.myqcloud.com/

  #开启aop日志记录，并将其输出到数据库中
  aop:
    auto: true


#mybatis的配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#配置分页
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

server:
  max-http-header-size: 102400
